version: '3.3'

services:
  redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379
  db:
    image: mysql
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root-1234
      MYSQL_DATABASE: hui
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa-1234
    volumes:
      - ./local-data/mysql:/var/lib/mysql
      - ./init-db-sql/grant.sql:/docker-entrypoint-initdb.d/1-init.sql
      #- ./mysql.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
  rabbit:
    image: rabbitmq:management
    restart: always
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "lsAPPLICATION"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "test"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    #volumes:
    #  - "./enabled-mq-plugins:/etc/rabbitmq/enabled_plugins"